# Generated by Django 5.2.4 on 2025-08-05 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('phase', models.CharField(choices=[('INICIO', 'Inicio de Turno'), ('DURANTE', 'Durante el Turno'), ('FIN', 'Finalización de Turno')], default='INICIO', max_length=10)),
                ('trigger_offset_minutes', models.PositiveIntegerField(default=0, help_text='Minutos desde el inicio del turno para que esta tarea sea relevante.')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Correo para notificaciones generales de la empresa.', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Conexión a Internet, Servidor de Archivos', max_length=100, unique=True)),
                ('ip_address', models.CharField(help_text='Dirección IP o dominio a monitorear', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Marcar para activar el monitoreo de este servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Turno Mañana, Turno Noche', max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.PositiveIntegerField(help_text='Duración del turno en horas (ej: 8, 12)')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Campamento Sarmiento, Bodega Central, Oficina Pta. Arenas', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shifttype')),
            ],
            options={
                'unique_together': {('operator', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_observation', models.TextField(blank=True, null=True, verbose_name='Observación Final del Operador')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Aprobación'), ('processed', 'Procesado y Enviado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to=settings.AUTH_USER_MODEL)),
                ('operator_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reports', to='core.operatorshift')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checklistitem')),
                ('operator_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='core.operatorshift')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(blank=True, help_text='Tiempo de respuesta en ms', null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.monitoredservice')),
            ],
        ),
        migrations.CreateModel(
            name='TraceabilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TurnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('pdf_report', models.FileField(upload_to='turn_reports/%Y/%m/%d/')),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_reports', to=settings.AUTH_USER_MODEL)),
                ('operator_shift', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn_report', to='core.operatorshift')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado de Aprobación')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.installation')),
                ('operator_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='core.operatorshift')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualRoundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('checked_installations', models.TextField(blank=True, help_text='Lista de instalaciones revisadas, separadas por comas', null=True)),
                ('operator_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_logs', to='core.operatorshift')),
            ],
        ),
    ]
