# Generated by Django 5.2.4 on 2025-07-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnreport',
            name='operator_shift',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn_report', to='core.operatorshift'),
        ),
    ]
