# Generated by Django 5.2.4 on 2025-07-26 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Conexión a Internet, Servidor de Archivos', max_length=100, unique=True)),
                ('ip_address', models.CharField(help_text='Dirección IP o dominio a monitorear', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Marcar para activar el monitoreo de este servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(blank=True, help_text='Tiempo de respuesta en ms', null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.monitoredservice')),
            ],
        ),
    ]
