# Generated by Django 5.2.4 on 2025-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_turnreport_operator_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Posición de la tarea en la lista'),
        ),
    ]
