# Generated by Django 5.2.4 on 2025-08-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_checklistitem_options_checklistitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='trigger_offset_minutes',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='dias_aplicables',
            field=models.CharField(blank=True, help_text='Días de la semana en que aplica la tarea (ej: 0,5 para Lunes y Sábado). Dejar en blanco para todos los días.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='turnos_aplicables',
            field=models.ManyToManyField(blank=True, help_text='Turnos en los que aplica la tarea. Dejar en blanco para todos los turnos.', to='core.shifttype'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripción de la Tarea'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='phase',
            field=models.CharField(choices=[('start', 'Inicio de Turno'), ('during', 'Durante el Turno'), ('end', 'Finalización de Turno')], default='during', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='checklistlog',
            unique_together={('operator_shift', 'item')},
        ),
    ]
