# Generated by Django 5.2.4 on 2025-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_checklistitem_trigger_offset_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['phase', 'order'], 'verbose_name': 'Ítem de Checklist', 'verbose_name_plural': 'Ítems de Checklist'},
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='alarm_trigger_delay',
            field=models.DurationField(blank=True, help_text="Establecer un tiempo para la alarma (ej: '1:30' para 1 hora y 30 mins) si la tarea no se completa. Se calcula desde el inicio del turno.", null=True, verbose_name='Alarma de Tarea Pendiente'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='dias_aplicables',
            field=models.CharField(blank=True, help_text='Marcar los días en que aplica. Dejar todos sin marcar para que aplique siempre.', max_length=50, null=True, verbose_name='Días de la Semana Aplicables'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Un número más bajo se muestra primero.', verbose_name='Orden de Visualización'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='phase',
            field=models.CharField(choices=[('start', 'Inicio de Turno'), ('during', 'Durante el Turno'), ('end', 'Finalización de Turno')], default='during', max_length=20, verbose_name='Fase del Turno'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='turnos_aplicables',
            field=models.ManyToManyField(blank=True, help_text='Marcar los turnos en que aplica. Dejar sin marcar para que aplique a todos.', to='core.shifttype', verbose_name='Tipos de Turno Aplicables'),
        ),
    ]
