# Generated by Django 5.2.4 on 2025-07-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monitoredservice_servicestatuslog'),
        ('core', '0004_seed_monitored_services'),
    ]

    operations = [
    ]
