# Generated by Django 5.2.4 on 2025-08-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_checklistitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='email',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='updatelog',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='¿Enviado en reporte?'),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado')], default='sent', max_length=10),
        ),
    ]
