# Generated by Django 5.2.4 on 2025-08-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_email_approved_at_remove_email_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelog',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='¿Ha sido editado?'),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='manual_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Manual del Evento'),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='original_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje Original'),
        ),
    ]
