# Generated by Django 5.2.4 on 2025-08-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_updatelog_edited_at_updatelog_is_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='manual_timestamp',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Manual del Evento'),
        ),
    ]
