# Generated by Django 5.2.4 on 2025-08-19 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_updatelog_manual_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Contacto (Ej: Ambulancia, Bomberos, Supervisor)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('company', models.ForeignKey(blank=True, help_text='Dejar en blanco si es un contacto general (Ej: Ambulancia).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='core.company')),
                ('installation', models.ForeignKey(blank=True, help_text='Opcional: especificar si este contacto es solo para una instalación.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='core.installation')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
                'ordering': ['company__name', 'installation__name', 'name'],
            },
        ),
    ]
