# Generated by Django 5.2.4 on 2025-08-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shiftnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Patente')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Conductor')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Camión'), ('van', 'Furgoneta'), ('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('other', 'Otro')], default='truck', max_length=50, verbose_name='Tipo de Vehículo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('speed', 'Exceso de Velocidad'), ('weather', 'Mal Clima'), ('traffic', 'Atascamiento'), ('route_cut', 'Corte de Ruta'), ('connection', 'Sin Conexión'), ('stopped', 'Tiempo Detenido Excesivo')], max_length=20, verbose_name='Tipo de Alerta')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Alerta de Vehículo',
                'verbose_name_plural': 'Alertas de Vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('speed', models.FloatField(default=0, verbose_name='Velocidad (km/h)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_connected', models.BooleanField(default=True, verbose_name='Conectado')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Posición de Vehículo',
                'verbose_name_plural': 'Posiciones de Vehículos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('start_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('total_distance', models.FloatField(default=0, verbose_name='Distancia Total (km)')),
                ('average_speed', models.FloatField(default=0, verbose_name='Velocidad Promedio (km/h)')),
                ('max_speed', models.FloatField(default=0, verbose_name='Velocidad Máxima (km/h)')),
                ('stop_time_minutes', models.IntegerField(default=0, verbose_name='Tiempo Detenido (minutos)')),
                ('weather_conditions', models.TextField(blank=True, null=True, verbose_name='Condiciones Climáticas')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Ruta de Vehículo',
                'verbose_name_plural': 'Rutas de Vehículos',
                'ordering': ['-start_time'],
            },
        ),
    ]
