# Generated by Django 5.2.4 on 2025-09-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vehicle_vehiclealert_vehicleposition_vehicleroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.TextField(blank=True, help_text='Correos para notificaciones, separados por comas.', null=True),
        ),
    ]
