# Generated by Django 5.2.4 on 2025-12-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorshift',
            name='monitored_companies',
            field=models.ManyToManyField(blank=True, help_text='Seleccione solo si el turno es restringido (ej: Mañana fin de semana). Deje vacío para monitorear TODAS.', related_name='assigned_shifts', to='core.company', verbose_name='Empresas Específicas'),
        ),
    ]
