# Generated by Django 5.2.4 on 2025-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_operatorshift_monitored_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='color',
            field=models.CharField(default='#CCCCCC', help_text='Código de color Hex (ej: #FF0000 para rojo)', max_length=7),
        ),
    ]
