# Generated by Django 5.2.4 on 2026-01-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shifttype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelog',
            name='attachment',
            field=models.FileField(blank=True, help_text='Formatos sugeridos: JPG, PNG, MP4', null=True, upload_to='novedades/%Y/%m/%d/', verbose_name='Adjunto (Foto/Video)'),
        ),
    ]
