# Generated by Django 5.2.4 on 2026-02-24 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_updatelog_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Sector')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción o Referencias')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='core.company', verbose_name='Empresa Asociada')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GPSIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text='Ej: Botón de Pánico, Ralentí, Colisión', max_length=100, verbose_name='Tipo de Alerta')),
                ('unit_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Unidad')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Patente')),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Conductor')),
                ('location_text', models.TextField(verbose_name='Ubicación (Texto)')),
                ('incident_timestamp', models.DateTimeField(verbose_name='Fecha y Hora del Incidente')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción (Sistema)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Resuelto'), ('ignored', 'Ignorado (Falso Positivo)')], default='pending', max_length=20, verbose_name='Estado')),
                ('who_answered', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Quién contestó la llamada?')),
                ('operator_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Resolución')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Resolución')),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, help_text='Calculado automáticamente al resolver.', null=True, verbose_name='Tiempo de Respuesta (Segundos)')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Operador que resolvió')),
                ('sector_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.sector', verbose_name='Sector Asignado')),
            ],
            options={
                'verbose_name': 'Incidente GPS',
                'verbose_name_plural': 'Incidentes GPS',
                'ordering': ['-incident_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SectorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Encargado')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Contacto de Sector',
                'verbose_name_plural': 'Contactos de Sector',
                'ordering': ['sector__name', 'name'],
            },
        ),
    ]
