# Generated by Django 5.2.4 on 2026-02-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sector_gpsincident_sectorcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsincident',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='gpsincident',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='gpsincident',
            name='maps_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Enlace de Google Maps'),
        ),
    ]
