# Generated by Django 5.2.4 on 2026-02-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_gpsincident_latitude_gpsincident_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant_emails', models.TextField(default='jefatura@tuempresa.cl', help_text='Separados por coma (,). Ej: jefe_turno@enap.cl, supervisor@selfing.cl', verbose_name='Correos para Alertas Instantáneas (Triage)')),
                ('monthly_emails', models.TextField(default='admin@tuempresa.cl', help_text='Separados por coma (,). Ej: gerencia@enap.cl, admin@selfing.cl', verbose_name='Correos para Reporte Mensual (Excel)')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones GPS',
                'verbose_name_plural': 'Configuración de Notificaciones GPS',
            },
        ),
    ]
