# Generated by Django 5.2.4 on 2026-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_gpsnotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='geofence_polygon',
            field=models.JSONField(blank=True, help_text='Formato: [[lat1, lon1], [lat2, lon2], [lat3, lon3], ...]', null=True, verbose_name='Coordenadas de la Geocerca'),
        ),
    ]
