# Generated by Django 5.2.4 on 2026-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sector_geofence_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsincident',
            name='cknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de toma del caso'),
        ),
        migrations.AlterField(
            model_name='gpsincident',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Codigo Enap'),
        ),
    ]
