# Generated by Django 5.2.4 on 2026-02-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_gpsincident_cknowledged_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsincident',
            old_name='cknowledged_at',
            new_name='taken_at',
        ),
    ]
