# Generated by Django 5.2.4 on 2026-02-27 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_cknowledged_at_gpsincident_taken_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco para tareas generales. Si se selecciona, aplica solo a turnos con esta empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa Asociada'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='installation',
            field=models.ForeignKey(blank=True, help_text='Seleccione si la tarea es específica para una sucursal/instalación particular.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.installation', verbose_name='Instalación Asociada'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_sequential',
            field=models.BooleanField(default=True, help_text='Si está marcado, el operador no podrá hacer esta tarea hasta completar la anterior.', verbose_name='Desbloqueo Secuencial'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='core.checklistitem', verbose_name='Tarea Principal (Sub-checklist)'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='requires_legal_check',
            field=models.BooleanField(default=True, help_text='Exige que el operador marque una casilla legal asumiendo la responsabilidad.', verbose_name='Requiere Declaración Jurada'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='checklist_photos/%Y/%m/%d/', verbose_name='Evidencia Fotográfica'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en segundos'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP del Operador'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='legal_agreement',
            field=models.BooleanField(default=False, verbose_name='Aceptó Declaración Jurada'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato: 12345678-9', max_length=12, null=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Aceptó Licencia de Uso'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='terms_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Aceptación'),
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de finalización'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OperatorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contrato', 'Contrato de Trabajo / Anexo'), ('terminos', 'Licencia de Uso Firmada (PDF)'), ('cert_antecedentes', 'Certificado de Antecedentes'), ('acuerdo_confidencialidad', 'Acuerdo de Confidencialidad (NDA)'), ('otro', 'Otro Documento')], default='otro', max_length=50, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='operator_docs/%Y/%m/%d/', verbose_name='Archivo Adjunto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Operador',
                'verbose_name_plural': 'Documentos de Operadores',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundInstallationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de revisión')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin de revisión')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='round_photos/%Y/%m/%d/', verbose_name='Captura de Pantalla/Foto')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.installation')),
                ('virtual_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_logs', to='core.virtualroundlog')),
            ],
            options={
                'verbose_name': 'Revisión de Instalación',
                'verbose_name_plural': 'Revisiones de Instalaciones',
                'ordering': ['start_time'],
            },
        ),
    ]
