# Generated by Django 5.2.4 on 2026-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_checklistitem_company_checklistitem_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistlog',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Segundos acumulados (Pausas)'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('paused', 'Pausada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración total final'),
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio o reanudación'),
        ),
    ]
