# Generated by Django 5.2.4 on 2026-02-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_checklistlog_accumulated_seconds_checklistlog_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistlog',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Segundos acumulados (Pausas)'),
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='legal_agreement',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aceptó Declaración Jurada'),
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('paused', 'Pausada'), ('completed', 'Completada')], default='pending', max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
