# Generated by Django 5.2.4 on 2026-02-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_checklistlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='unlock_delay',
            field=models.DurationField(blank=True, help_text="Tiempo desde el inicio del turno para que se habilite (ej: '02:00:00' para 2 horas). Déjalo en blanco para que esté disponible de inmediato.", null=True, verbose_name='Bloqueo por Tiempo'),
        ),
    ]
