# Generated by Django 5.2.4 on 2026-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_checklistitem_unlock_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundinstallationlog',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Segundos acumulados (Pausas)'),
        ),
        migrations.AddField(
            model_name='roundinstallationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('paused', 'Pausada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='roundinstallationlog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración Total'),
        ),
    ]
