# Generated by Django 5.2.4 on 2026-02-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_roundinstallationlog_accumulated_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='installation',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='installations',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una o más sucursales/instalaciones. Si deja en blanco, aplica a todas las de la empresa.', to='core.installation', verbose_name='Instalaciones Asociadas'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='specific_time',
            field=models.TimeField(blank=True, help_text='Si se define, la tarea se habilitará a esta hora exacta (ej: 14:30).', null=True, verbose_name='Hora Específica'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='alarm_trigger_delay',
            field=models.DurationField(blank=True, null=True, verbose_name='Alarma de Tarea Pendiente'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa Asociada'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='dias_aplicables',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Días de la Semana Aplicables'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='is_sequential',
            field=models.BooleanField(default=True, verbose_name='Desbloqueo Secuencial'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='core.checklistitem', verbose_name='Tarea Principal'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='phase',
            field=models.CharField(choices=[('1_start', 'Inicio de Turno'), ('2_during', 'Durante el Turno'), ('3_end', 'Finalización de Turno')], default='2_during', max_length=20, verbose_name='Fase del Turno'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='requires_legal_check',
            field=models.BooleanField(default=True, verbose_name='Requiere Declaración Jurada'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='turnos_aplicables',
            field=models.ManyToManyField(blank=True, to='core.shifttype', verbose_name='Tipos de Turno Aplicables'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='unlock_delay',
            field=models.DurationField(blank=True, help_text='Tiempo desde el inicio del turno para que se habilite.', null=True, verbose_name='Bloqueo por Tiempo'),
        ),
    ]
