# Generated by Django 5.2.4 on 2026-02-28 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_checklistitem_installation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='installations',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='specific_time',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='installation',
            field=models.ForeignKey(blank=True, help_text='Seleccione si la tarea es específica para una sucursal/instalación particular.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.installation', verbose_name='Instalación Asociada'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='alarm_trigger_delay',
            field=models.DurationField(blank=True, help_text="Establecer un tiempo para la alarma (ej: '1:30' para 1 hora y 30 mins) si la tarea no se completa. Se calcula desde el inicio del turno.", null=True, verbose_name='Alarma de Tarea Pendiente'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco para tareas generales. Si se selecciona, aplica solo a turnos con esta empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa Asociada'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='dias_aplicables',
            field=models.CharField(blank=True, help_text='Marcar los días en que aplica. Dejar todos sin marcar para que aplique siempre.', max_length=50, null=True, verbose_name='Días de la Semana Aplicables'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='is_sequential',
            field=models.BooleanField(default=True, help_text='Si está marcado, el operador no podrá hacer esta tarea hasta completar la anterior.', verbose_name='Desbloqueo Secuencial'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='core.checklistitem', verbose_name='Tarea Principal (Sub-checklist)'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='phase',
            field=models.CharField(choices=[('start', 'Inicio de Turno'), ('during', 'Durante el Turno'), ('end', 'Finalización de Turno')], default='during', max_length=20, verbose_name='Fase del Turno'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='requires_legal_check',
            field=models.BooleanField(default=True, help_text='Exige que el operador marque una casilla legal asumiendo la responsabilidad.', verbose_name='Requiere Declaración Jurada'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='turnos_aplicables',
            field=models.ManyToManyField(blank=True, help_text='Marcar los turnos en que aplica. Dejar sin marcar para que aplique a todos.', to='core.shifttype', verbose_name='Tipos de Turno Aplicables'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='unlock_delay',
            field=models.DurationField(blank=True, help_text="Tiempo desde el inicio del turno para que se habilite (ej: '02:00:00' para 2 horas). Déjalo en blanco para que esté disponible de inmediato.", null=True, verbose_name='Bloqueo por Tiempo'),
        ),
    ]
