# Generated by Django 5.2.4 on 2026-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_checklistitem_installations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='specific_time',
            field=models.TimeField(blank=True, help_text='Si se define, la tarea se habilitará a esta hora exacta (ej: 14:30).', null=True, verbose_name='Hora Específica'),
        ),
    ]
