# Generated by Django 5.2.4 on 2026-03-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_checklistitem_specific_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='installations',
            field=models.ManyToManyField(blank=True, help_text='Seleccione las instalaciones para generar subtareas cronometradas automáticamente.', related_name='checklist_items', to='core.installation', verbose_name='Múltiples Instalaciones'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='installation',
            field=models.ForeignKey(blank=True, help_text='[MANTENER POR COMPATIBILIDAD] Use el nuevo selector múltiple de abajo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_checklist_items', to='core.installation', verbose_name='Instalación (Antiguo/No usar)'),
        ),
    ]
